basics:
- curl
- git
- lsb-release
- ca-certificates
- build-essential

ssh:
  generate: true

apps:
  # https://docs.docker.com/engine/install/ubuntu/
  # https://docs.docker.com/engine/install/linux-postinstall/
  docker:
    gpg:
      key: https://download.docker.com/linux/ubuntu/gpg
      tee: https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable
    install:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-compose-plugin
    post-install:
    - groupadd docker
    - usermod -aG docker $USER
  
  # https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/
  kubernetes:
    gpg:
      key: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      tee: https://apt.kubernetes.io/ kubernetes-xenial main
    install:
    # - kubeadm
    # - kubelet
    - kubectl
    post-install:
    - swapoff -a # turn off swap
    - sed -i '/ swap / s/^/#/' /etc/fstab
  
  python:
    install:
    - python-is-python3
    - python3-pip
    - python3-venv
